### ISSUE TITLE
Battery Board V4 Development

### ISSUE THREAD

**Issue by Mikefly123** [proveskit/battery_board#13]
For the PROVES Kit V2 we are planning a complete overhaul of the Battery Board. 

Here are some of the planned changes in the new version: 
- [ ] Connector Overhaul 
- [ ] Battery Holder Update
- [ ] Updated Burn Wire and Heater Circuit
- [ ] Camera System Load Switching 
- [ ] Improved Watchdog System
